// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYhZYZpKpF2FIbpBeZSOP8YE1uKtb1pqk',
    appId: '1:667684537520:web:a5645ac79eade53c232775',
    messagingSenderId: '667684537520',
    projectId: 'eyob-twitter-clone',
    authDomain: 'eyob-twitter-clone.firebaseapp.com',
    storageBucket: 'eyob-twitter-clone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7tJIinVEuR2PMGi1s97G7SpWzaClHaRQ',
    appId: '1:667684537520:android:6c28e400a6800644232775',
    messagingSenderId: '667684537520',
    projectId: 'eyob-twitter-clone',
    storageBucket: 'eyob-twitter-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpgRFzjl1Cqm0olGRC-XraaFRLViuGqFI',
    appId: '1:667684537520:ios:979f7aac3882a149232775',
    messagingSenderId: '667684537520',
    projectId: 'eyob-twitter-clone',
    storageBucket: 'eyob-twitter-clone.appspot.com',
    iosBundleId: 'com.example.twitterClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpgRFzjl1Cqm0olGRC-XraaFRLViuGqFI',
    appId: '1:667684537520:ios:72cc7adbc71d5a1a232775',
    messagingSenderId: '667684537520',
    projectId: 'eyob-twitter-clone',
    storageBucket: 'eyob-twitter-clone.appspot.com',
    iosBundleId: 'com.example.twitterClone.RunnerTests',
  );
}
